### ISSUE TITLE
Fixing unsafe unwraps in subcommand

### ISSUE THREAD

**Issue by vedangj044** [drogue-iot/cli#3]
The use of `unwrap` to parse the subcommands often causes panic, thus is unsafe. Instead `match matches.subcommand() {}` is a better option.

Reference can be found [here](https://github.com/clap-rs/clap/blob/52814b893c87e1c0350cae13fc1988fe2aa9886a/examples/20_subcommands.rs#L123)

An example of the proposed solution can be 

```
match matches.subcommand() {
    ("create", Some(create_subcommand)) => {
        
        match create_subcommand.subcommand() {
            ("app", Some(app_command)) => {
                let data = util::json_parse(app_command.value_of(Parameters::data))?;
                let id = app_command.value_of(Parameters::id).unwrap();
                apps::create(&url, id, data)?
            }
            ("device", Some(device_command)) => {
                let data = util::json_parse(device_command.value_of(Parameters::data))?;
                let id = device_command.value_of(Parameters::id).unwrap();
                let app_id = device_command.value_of(Resources::app).unwrap();
                devices::create(&url, id, data, app_id)?
            }
            _ => println!("a")
        }

    }
```

I would like to work on this issue.

**Comment by jbtrystram** [comment]
Indeed i had wrote a TODO to repleace those unsafe unwraps. The proposed solution looks better ! Thanks for looking into it

**Comment by vedangj044** [comment]
Yeah, I saw your TODO. There are still more TODO notes, I can try fixing those in the next few days. :-)
